INSERT INTO CLIENTE(DNI, NOMBRE) VALUES (12654789, 'PEPE ARGENTO');
INSERT INTO CLIENTE(DNI, NOMBRE) VALUES (45875154, 'JUAN DI SEO');
INSERT INTO CLIENTE(DNI, NOMBRE) VALUES (4654782, 'PEDRO PICAGUA');
INSERT INTO CLIENTE(DNI, NOMBRE) VALUES (35159456, 'ANDRES ACEVEDO');
INSERT INTO CLIENTE(DNI, NOMBRE) VALUES (23345654, 'DIEGO RAMOS');
INSERT INTO CLIENTE(DNI, NOMBRE) VALUES (32346834, 'LEO LEYES');
INSERT INTO CLIENTE(DNI, NOMBRE) VALUES (35159456, 'MARIANO MORENO');

INSERT INTO PRODUCTO (DESCRIPCION, PRECIO) VALUES ('CELULAR',20058);
INSERT INTO PRODUCTO (DESCRIPCION, PRECIO) VALUES ('TELEVISOR',105023);
INSERT INTO PRODUCTO (DESCRIPCION, PRECIO) VALUES ('PARLANTE',7895);
INSERT INTO PRODUCTO (DESCRIPCION, PRECIO) VALUES ('AURICULARES',957);
INSERT INTO PRODUCTO (DESCRIPCION, PRECIO) VALUES ('TECLADO',1457);
INSERT INTO PRODUCTO (DESCRIPCION, PRECIO) VALUES ('MOUSE',1765);
INSERT INTO PRODUCTO (DESCRIPCION, PRECIO) VALUES ('PILAS AAA',345);
INSERT INTO PRODUCTO (DESCRIPCION, PRECIO) VALUES ('ROUTER',2765);
INSERT INTO PRODUCTO (DESCRIPCION, PRECIO) VALUES ('VAPEADOR',5365);
INSERT INTO PRODUCTO (DESCRIPCION, PRECIO) VALUES ('GUITARRA',22765);
INSERT INTO PRODUCTO (DESCRIPCION, PRECIO) VALUES ('BAJO',18365);
INSERT INTO PRODUCTO (DESCRIPCION, PRECIO) VALUES ('RELOJ',4765);
INSERT INTO PRODUCTO (DESCRIPCION, PRECIO) VALUES ('SINTETIZADOR',15565);


INSERT INTO TIPO_CARRITO (DESCRIPCION) VALUES ('COMUN'); 
INSERT INTO TIPO_CARRITO (DESCRIPCION) VALUES ('FECHA ESPECIAL'); 
INSERT INTO TIPO_CARRITO (DESCRIPCION) VALUES ('VIP'); 

INSERT INTO CARRITO(FECHA_CREACION,CLIENTE_ID, TIPO_CARRITO_ID) VALUES (NOW(),1,1);
INSERT INTO CARRITO_PRODUCTO(CARRITO_ID, PRODUCTO_ID) VALUES(1,1);
INSERT INTO CARRITO_PRODUCTO(CARRITO_ID, PRODUCTO_ID) VALUES(1,2);

INSERT INTO CARRITO(FECHA_CREACION,CLIENTE_ID, TIPO_CARRITO_ID) VALUES (NOW(),2,2);
INSERT INTO CARRITO_PRODUCTO(CARRITO_ID, PRODUCTO_ID) VALUES(2,2);
INSERT INTO CARRITO_PRODUCTO(CARRITO_ID, PRODUCTO_ID) VALUES(2,3);
INSERT INTO CARRITO_PRODUCTO(CARRITO_ID, PRODUCTO_ID) VALUES(2,4);

INSERT INTO CARRITO(FECHA_CREACION,CLIENTE_ID, TIPO_CARRITO_ID) VALUES (NOW(),3,3);
INSERT INTO CARRITO_PRODUCTO(CARRITO_ID, PRODUCTO_ID) VALUES(3,4);

INSERT INTO CARRITO(FECHA_CREACION,CLIENTE_ID, TIPO_CARRITO_ID) VALUES (NOW(),4,1);
INSERT INTO CARRITO_PRODUCTO(CARRITO_ID, PRODUCTO_ID) VALUES(4,1);
INSERT INTO CARRITO_PRODUCTO(CARRITO_ID, PRODUCTO_ID) VALUES(4,2);
INSERT INTO CARRITO_PRODUCTO(CARRITO_ID, PRODUCTO_ID) VALUES(4,3);
INSERT INTO CARRITO_PRODUCTO(CARRITO_ID, PRODUCTO_ID) VALUES(4,4);
INSERT INTO CARRITO_PRODUCTO(CARRITO_ID, PRODUCTO_ID) VALUES(4,5);
INSERT INTO CARRITO_PRODUCTO(CARRITO_ID, PRODUCTO_ID) VALUES(4,6);
INSERT INTO CARRITO_PRODUCTO(CARRITO_ID, PRODUCTO_ID) VALUES(4,7);
INSERT INTO CARRITO_PRODUCTO(CARRITO_ID, PRODUCTO_ID) VALUES(4,8);
INSERT INTO CARRITO_PRODUCTO(CARRITO_ID, PRODUCTO_ID) VALUES(4,9);
INSERT INTO CARRITO_PRODUCTO(CARRITO_ID, PRODUCTO_ID) VALUES(4,10);
INSERT INTO CARRITO_PRODUCTO(CARRITO_ID, PRODUCTO_ID) VALUES(4,11);

INSERT INTO CARRITO(FECHA_CREACION,CLIENTE_ID, TIPO_CARRITO_ID) VALUES (NOW(),5,2);
INSERT INTO CARRITO_PRODUCTO(CARRITO_ID, PRODUCTO_ID) VALUES(5,8);
INSERT INTO CARRITO_PRODUCTO(CARRITO_ID, PRODUCTO_ID) VALUES(5,5);
INSERT INTO CARRITO_PRODUCTO(CARRITO_ID, PRODUCTO_ID) VALUES(5,11);
